export const Users = [
  {
    username: "Jenna Davis",
    title: "Blogger",
    location: "Melbourne",
    user_id: 0,
    common_friends: 21,
    first_friend: "Alan Maynard",
    second_friend: "Margaret Bowles",
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Dan Walker",
    title: "Developer",
    location: "New york",
    user_id: 1,
    common_friends: 4,
    first_friend: "Nathan Jones",
    second_friend: "Margaret Bowles",
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Stella Bergmann",
    title: "Student",
    location: "Berlin",
    user_id: 2,
    common_friends: 48,
    first_friend: "Adam Wathan",
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Daniel Wellington",
    title: "",
    location: "London",
    user_id: 3,
    common_friends: 5,
    first_friend: "Nathan jones",
    second_friend: "Anna Mitchells",
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "David Kim",
    title: "",
    location: "Chicago",
    user_id: 4,
    common_friends: 0,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Edward Mayers",
    title: "",
    location: "Dublin",
    user_id: 5,
    common_friends: 35,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Elise Walker",
    title: "",
    location: "London",
    user_id: 6,
    common_friends: 1,
    first_friend: "Dan Walker",
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Milly Augustine",
    title: "",
    location: "Rome",
    user_id: 7,
    common_friends: 3,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Bobby Brown",
    title: "",
    location: "Paris",
    user_id: 8,
    common_friends: 11,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Nelly Schwartz",
    title: "",
    location: "Melbourne",
    user_id: 9,
    common_friends: 11,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Lana Henrikssen",
    title: "",
    location: "Helsinki",
    user_id: 10,
    common_friends: 11,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Gaelle Morris",
    title: "",
    location: "Lyon",
    user_id: 11,
    common_friends: 11,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Mike Lasalle",
    title: "",
    location: "Toronto",
    user_id: 12,
    common_friends: 11,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Rolf Krupp",
    title: "",
    location: "Berlin",
    user_id: 13,
    common_friends: 11,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Ken Rogers",
    title: "",
    location: "Chicago",
    user_id: 14,
    common_friends: 9,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Leana Marks",
    title: "",
    location: "Nashville",
    user_id: 15,
    common_friends: 0,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Aline Cambell",
    title: "",
    location: "Seattle",
    user_id: 16,
    common_friends: 0,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Mike Donovan",
    title: "",
    location: "San Francisco",
    user_id: 17,
    common_friends: 0,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "George A. Romero",
    title: "",
    location: "Los Angeles",
    user_id: 18,
    common_friends: 0,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Brian Stevenson",
    title: "",
    location: "San Diego",
    user_id: 19,
    common_friends: 0,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Azzouz El Paytoun",
    title: "",
    location: "Montreal",
    user_id: 20,
    common_friends: 0,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Cathy Smith",
    title: "",
    location: "Seattle",
    user_id: 21,
    common_friends: 0,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Bob Barker",
    title: "",
    location: "Tijuana",
    user_id: 22,
    common_friends: 0,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Greg Patel",
    title: "",
    location: "Bogota",
    user_id: 23,
    common_friends: 0,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
  {
    username: "Hisashi Yokida",
    title: "",
    location: "Tokyo",
    user_id: 24,
    common_friends: 0,
    first_friend: null,
    second_friend: null,
    profile_picture: "https://via.placeholder.com/150x150",
    cover_image: "https://via.placeholder.com/400x150",
  },
];

export const Posts = [
  {
    id: 1,
    userId: 1,
    content:
      "Yesterday with @Karen Miller and @Marvin Stemperd at the #Rock'n'Rolla concert in LA. Was totally fantastic! People were really excited about this one!",
    photo: "https://via.placeholder.com/1600x900",
    link: "",
    time: "July 26 2018, 01:03pm",
    like: 23,
    share: 9,
    comment: 3,
  },
  {
    id: 2,
    userId: 5,
    content:
      "You all know how i love bootstrap, but i didn't have time to dig deeper into it. Therefore i found this very interesting video i wanted to share with you all. #bootsrap #webdesign",
    photo: "",
    link: "https://www.youtube.com/watch?v=N8GksI_-iIM",
    time: "July 26 2018, 11:14am",
    like: 2,
    share: 0,
    comment: 2,
  },
];